In [2]:
import torch
torch.__version__

'1.11.0+cpu'

# numpy

In [6]:
import numpy as np
arr1 = np.array([1])
arr2 = np.array([[1,2],[3,4]])
print(arr1)
print(arr2)

[1]
[[1 2]
 [3 4]]


In [3]:
torch.rand(2, 3, 5)

tensor([[[0.0458, 0.2616, 0.9006, 0.7936, 0.0511],
         [0.2091, 0.3169, 0.1952, 0.2808, 0.7705],
         [0.6189, 0.4383, 0.7668, 0.1305, 0.9359]],

        [[0.8848, 0.1649, 0.7079, 0.2253, 0.5501],
         [0.2781, 0.6249, 0.7895, 0.7690, 0.2740],
         [0.1954, 0.1995, 0.0773, 0.1140, 0.3104]]])

In [8]:
np.arange(4)

array([0, 1, 2, 3])

In [9]:
np.arange(4,6)

array([4, 5])

In [10]:
print(arr1.ndim)
print(arr2.ndim)

1
2


In [11]:
print(arr1.shape)
print(arr2.shape)

(1,)
(2, 2)


In [12]:
arr2.reshape((4,1))

array([[1],
       [2],
       [3],
       [4]])

In [14]:
arr3 = np.arange(6).reshape(2,3)
print(arr3)

[[0 1 2]
 [3 4 5]]


In [15]:
arr3.size

6

In [16]:
arr3.shape

(2, 3)

In [17]:
arr3.dtype

dtype('int32')

In [18]:
arr4 = np.array([[1,2],[3,4]],dtype = 'float')
arr4.dtype

dtype('float64')

In [19]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [22]:
np.linspace(start=2,stop=10,num=3)

array([ 2.,  6., 10.])

In [23]:
arr4 = np.random.rand(2,3)
print(arr4)

[[0.80687849 0.15498559 0.44349738]
 [0.30945798 0.57235674 0.93584537]]


In [24]:
arr5 = np.random.randint(10,size=(4,3))
arr5

array([[0, 9, 1],
       [7, 6, 7],
       [6, 3, 6],
       [1, 2, 5]])

In [27]:
np.sum(arr5,axis=0)

array([14, 20, 19])