In [1]:
import numpy as np

t1

In [7]:
import torch
ar1 = np.random.rand(5,5)
arr1 = torch.tensor(ar1)
arr1

tensor([[0.9049, 0.4677, 0.9413, 0.7978, 0.6720],
        [0.9529, 0.5014, 0.9084, 0.0219, 0.7301],
        [0.2615, 0.6619, 0.8186, 0.4766, 0.8177],
        [0.7392, 0.5154, 0.4900, 0.9360, 0.9597],
        [0.6075, 0.0036, 0.4412, 0.5730, 0.5594]], dtype=torch.float64)

In [10]:
arr1[0,:]

tensor([0.9049, 0.4677, 0.9413, 0.7978, 0.6720], dtype=torch.float64)

In [11]:
arr1[:,-2]

tensor([0.7978, 0.0219, 0.4766, 0.9360, 0.5730], dtype=torch.float64)

t2

In [16]:
x = torch.arange(4).view(4,1)
x

tensor([[0],
        [1],
        [2],
        [3]])

In [17]:
y = torch.arange(2).view(1,2)
y

tensor([[0, 1]])

In [25]:
z = x + y
z

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]])

In [26]:
z = z.transpose(1,0)
z

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4]])

t3

In [27]:
import pandas as pd

In [48]:
#原始数据
data = pd.read_csv('iris-example.csv')
data

sepal_length  sepal_width  petal_length  petal_width            class
0            5.1          3.5           1.4          NaN      Iris-setosa
1            4.9          3.0           1.4          NaN      Iris-setosa
2            4.7          3.2           1.3          1.0      Iris-setosa
3            4.6          3.1           1.5          NaN      Iris-setosa
4            5.0          3.6           1.4          NaN      Iris-setosa
5            7.0          3.2           NaN          NaN  Iris-versicolor
6            6.4          3.2           4.5          1.0  Iris-versicolor
7            6.9          3.1           4.9          2.0  Iris-versicolor
8            5.5          2.3           4.0          2.0  Iris-versicolor
9            6.5          NaN           4.6          2.0  Iris-versicolor
10           6.3          3.3           6.0          2.0   Iris-virginica
11           5.8          2.7           5.1          NaN   Iris-virginica
12           7.1          NaN           5.9          NaN   Iris-virginica
13           6.3          2.9           5.6          NaN   Iris-virginica
14           6.5          3.0           NaN          NaN   Iris-virginica

In [49]:
#填充后数据
data.iloc[:,0:4] = data.iloc[:,0:4].fillna(data.mean(numeric_only=True))
data

sepal_length  sepal_width  petal_length  petal_width            class
0            5.1     3.500000      1.400000     1.666667      Iris-setosa
1            4.9     3.000000      1.400000     1.666667      Iris-setosa
2            4.7     3.200000      1.300000     1.000000      Iris-setosa
3            4.6     3.100000      1.500000     1.666667      Iris-setosa
4            5.0     3.600000      1.400000     1.666667      Iris-setosa
5            7.0     3.200000      3.661538     1.666667  Iris-versicolor
6            6.4     3.200000      4.500000     1.000000  Iris-versicolor
7            6.9     3.100000      4.900000     2.000000  Iris-versicolor
8            5.5     2.300000      4.000000     2.000000  Iris-versicolor
9            6.5     3.084615      4.600000     2.000000  Iris-versicolor
10           6.3     3.300000      6.000000     2.000000   Iris-virginica
11           5.8     2.700000      5.100000     1.666667   Iris-virginica
12           7.1     3.084615      5.900000     1.666667   Iris-virginica
13           6.3     2.900000      5.600000     1.666667   Iris-virginica
14           6.5     3.000000      3.661538     1.666667   Iris-virginica